title: My Bible Blog
description: A simple weekly blog to  help me stay on track with my Bible Reading.
baseurl: ""  # Leave empty for root domain, or set if deploying in a subfolder
url: "https://zach-and-mickey.github.io"  # Your GitHub Pages URL
baseurl: "/my-blog"
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
sass: 
  style: compressed
